site_name: StreamerTools

# Meta tags (placed in header)
site_description: 
site_author: Diatorker
site_url: ""# https://you.github.io/StreamerTools
use_directory_urls: false

# Repository (add link to repository on each page)
repo_name: StreamerTools
repo_url: https://github.com/Diatorker/StreamerTools
edit_uri: edit/main/src/doc/docs/

#Copyright (shown at the footer)
copyright: 'Copyright &copy; 2022 Diatorker'

# Meterial theme
theme:
  name: 'material'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.instant
    - navigation.tracking
    - navigation.top

plugins: []
#  - search
#    Required for variables support (https://github.com/rosscdh/mkdocs-markdownextradata-plugin)
#  - markdownextradata

#extra:
#  palette:
#    primary: 'indigo'
#    accent: 'indigo'

#  version:
#    provider: mike

#  social:
#    - icon: fontawesome/brands/github
#      link: https://github.com/you
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/you
#
# Google Analytics
#  analytics:
#    provider: google
#    property: UA-XXXXXXXX-X

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Dev server binding
#dev_addr: 127.0.0.1:3001

nav:
  - Accueil: index.md
  - User guide:
      - Installation: guide/installation.md
      - Utilisation:
          - Personnalisation: guide/utilisation/personnalisation.md
          - Youtube: guide/utilisation/youtube.md
          - Spotify: guide/utilisation/spotify.md
          - Timer: guide/utilisation/timer.md